[package]
name = "threadpool"
version = "0.1.0"
edition = "2021"

[features]
default = []
dashmap = ["dep:dashmap"]

[dependencies]
thiserror = "1.0.52"
tracing = "0.1.40"
dashmap = { version = "5.5.3", optional = true }
